package modelos;
// Generated 28/06/2017 23:16:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer generoId;
     private String nome;
     private Set filmeses = new HashSet(0);

    public Genero() {
    }

    public Genero(String nome, Set filmeses) {
       this.nome = nome;
       this.filmeses = filmeses;
    }
   
    public Integer getGeneroId() {
        return this.generoId;
    }
    
    public void setGeneroId(Integer generoId) {
        this.generoId = generoId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getFilmeses() {
        return this.filmeses;
    }
    
    public void setFilmeses(Set filmeses) {
        this.filmeses = filmeses;
    }
    
}


